# Generated by Django 4.0.5 on 2022-07-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_status_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
