# Generated by Django 4.0.5 on 2022-07-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('advertisements', '0004_advertisement_draft_alter_advertisement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', through='advertisements.Favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourites',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user', to='advertisements.advertisement'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_adv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('advertisement', 'user'), name='unique favourites'),
        ),
    ]
