# Generated by Django 4.0.5 on 2022-07-18 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('advertisements', '0005_favourites_advertisement_favourites_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique favourites',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='favourites',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite', through='advertisements.Favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
